// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yglllvordvxufsfdatqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbGxsdm9yZHZ4dWZzZmRhdHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDg4NDQsImV4cCI6MjA3Njk4NDg0NH0.XWMCLavaXzCh5LBZhx3AuIfCxMrwTZuXahUMblqOU1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});